name: Reusable python type check

on:
  workflow_call:

jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: mypy
          mypy-version: "1.8.0"
          python-version: '3.11'
