name: Reusable python lint

on:
  workflow_call:

jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: ruff
          ruff-version: "0.2.1"
