name: Reusable python lint

on:
  workflow_call:

jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.6'
          cache: 'poetry'
      - run: |
          poetry install --only dev && \
          ruff src tests