name: Main workflow

on:
  pull_request:
    branches: [ "master" ]
jobs:
  lint:
    uses: ./.github/workflows/python-3.11.6-lint.yml
  type-check:
    uses: ./.github/workflows/python-3.11.6-type-check.yml
